In [1]:
import pandas as pd
data = [{'a':1, 'b':2}, {'a':5, 'b':10, 'c':20}]
df = pd.DataFrame(data)
df

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [24]:
dados = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
        'two': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(dados)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [25]:
df['three'] = pd.Series([10., 20., 30.], index=['a', 'b', 'c'])
df

   one  two  three
a  1.0  1.0   10.0
b  2.0  2.0   20.0
c  3.0  3.0   30.0
d  NaN  4.0    NaN

In [26]:
df['four'] = df['three']
df

   one  two  three  four
a  1.0  1.0   10.0  10.0
b  2.0  2.0   20.0  20.0
c  3.0  3.0   30.0  30.0
d  NaN  4.0    NaN   NaN

In [19]:
del df['two']
df # exlusão de coluna utilizando a função DEL

   one  three  four
a  1.0   10.0  10.0
b  2.0   20.0  20.0
c  3.0   30.0  30.0
d  NaN    NaN   NaN

In [23]:
df.pop('three')
df # exclusão de coluna utilizando a função POP

   one  two  four
a  1.0  1.0  10.0
b  2.0  2.0  20.0
c  3.0  3.0  30.0
d  NaN  4.0   NaN