In [32]:
import pandas as pd

salario = pd.read_csv('salarios_1.csv')
salario

                 Nome  Idade     Salário
0       Colby Bezerra     39   $3,655.82
1     Raphael Caetano     28   $3,434.08
2      Vivien Moreira     44   $5,758.39
3     Dominic Pacheco     18   $6,746.30
4      Colorado Felix     53   $5,120.70
5         Lucy Borges     38   $8,357.69
6          Levi Alves     41   $9,724.53
7       Joseph Nonato     32   $2,410.71
8       Kenyon Cabral     33   $9,532.24
9        Quinn Vieira     43   $9,148.76
10  Ferris de Andrade     54  $10,287.78
11    Giselle Ribeiro     48   $7,651.70
12   Chancellor Viana     38   $7,849.33
13         Troy Faria     55   $3,496.81
14    Delilah Bezerra     42  $10,270.19

In [33]:
salario['Salário_Float'] = salario['Salário'].replace('[\$,]','',regex=True).astype(float)

<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\Aluno\AppData\Local\Temp\ipykernel_5836\1186617395.py:1: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  salario['Salário_Float'] = salario['Salário'].replace('[\$,]','',regex=True).astype(float)

In [34]:
print(salario.loc[:,['Nome']])

                 Nome
0       Colby Bezerra
1     Raphael Caetano
2      Vivien Moreira
3     Dominic Pacheco
4      Colorado Felix
5         Lucy Borges
6          Levi Alves
7       Joseph Nonato
8       Kenyon Cabral
9        Quinn Vieira
10  Ferris de Andrade
11    Giselle Ribeiro
12   Chancellor Viana
13         Troy Faria
14    Delilah Bezerra

In [35]:
coluna1 = salario.loc[:,['Nome']]
coluna1

                 Nome
0       Colby Bezerra
1     Raphael Caetano
2      Vivien Moreira
3     Dominic Pacheco
4      Colorado Felix
5         Lucy Borges
6          Levi Alves
7       Joseph Nonato
8       Kenyon Cabral
9        Quinn Vieira
10  Ferris de Andrade
11    Giselle Ribeiro
12   Chancellor Viana
13         Troy Faria
14    Delilah Bezerra

In [39]:
coluna2 = salario.rename(columns={'Nome':'Colaborador(a)'}).head()
coluna2

    Colaborador(a)  Idade    Salário  Salário_Float
0    Colby Bezerra     39  $3,655.82        3655.82
1  Raphael Caetano     28  $3,434.08        3434.08
2   Vivien Moreira     44  $5,758.39        5758.39
3  Dominic Pacheco     18  $6,746.30        6746.30
4   Colorado Felix     53  $5,120.70        5120.70

In [40]:
mais_novo = salario.loc[salario['Idade']==salario['Idade'].min()]
mais_novo

              Nome  Idade    Salário  Salário_Float
3  Dominic Pacheco     18  $6,746.30         6746.3

In [41]:
maior_salario = salario.loc[salario['Salário']==salario['Salário'].max()]
maior_salario

         Nome  Idade    Salário  Salário_Float
6  Levi Alves     41  $9,724.53        9724.53

In [42]:
mais_velho = salario.loc[salario['Idade']==salario['Idade'].max()]
mais_velho

          Nome  Idade    Salário  Salário_Float
13  Troy Faria     55  $3,496.81        3496.81

In [43]:
mediaIdade = salario['Idade'].mean()
print(mediaIdade)

40.4

In [44]:
mediaSalario = round(salario['Salário'].mean(),2)
mediaSalario

TypeError: Cannot perform reduction 'mean' with string dtype